### ISSUE TITLE
npm start报错

### ISSUE THREAD

**Issue by cj768025549** [sealtalk/sealtalk-desktop#1]
以下是错误信息：

xiaobaizhude-MacBook-Pro:sealtalk-desktop changjian$ npm start

> SealTalk@1.0.2 start /Users/changjian/GitHub/sealtalk-desktop
> electron main.js --enable-logging

fs.js:634
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/changjian/GitHub/sealtalk-desktop/node_modules/electron-prebuilt/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at Object.<anonymous> (/Users/changjian/GitHub/sealtalk-desktop/node_modules/electron-prebuilt/index.js:4:42)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.2.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! SealTalk@1.0.2 start: `electron main.js --enable-logging`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the SealTalk@1.0.2 start script 'electron main.js --enable-logging'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the SealTalk package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js --enable-logging
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs SealTalk
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls SealTalk
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/changjian/GitHub/sealtalk-desktop/npm-debug.log

**Comment by hwswin** [comment]
我的有sealtalk-desktop\node_modules\electron-prebuilt\path.txt
你再npm install一下，可能就有了？

**Comment by YongHao0** [comment]
此项目已废弃, 新版请参考: https://www.rongcloud.cn/docs/desktop
